version: 2.1

workflows:
  testing-bitbucket:
    jobs:
      - testing-bitbucket

jobs:
  testing-bitbucket:
    docker:
      - image: cimg/base:2022.06
    resource_class: medium
    steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
              - ""
        - run: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
        - run: git clone git@bitbucket.org:imlogang/testing.git